package com.yodobashi.esa.cms.getupdatedata;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-16T15:04:37.873+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "GetUpdateDataService", 
                  wsdlLocation = "file:/C:/workspace/catalog_ws/YC_COMMUNITY_DATASYNC/src/main/resources/wsdl/GetUpdateData20070731.wsdl",
                  targetNamespace = "http://esa.yodobashi.com/CMS/GetUpdateData") 
public class GetUpdateDataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/CMS/GetUpdateData", "GetUpdateDataService");
    public final static QName GetUpdateDataPort = new QName("http://esa.yodobashi.com/CMS/GetUpdateData", "GetUpdateDataPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/catalog_ws/YC_COMMUNITY_DATASYNC/src/main/resources/wsdl/GetUpdateData20070731.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetUpdateDataService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/catalog_ws/YC_COMMUNITY_DATASYNC/src/main/resources/wsdl/GetUpdateData20070731.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetUpdateDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetUpdateDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetUpdateDataService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetUpdateData
     */
    @WebEndpoint(name = "GetUpdateDataPort")
    public GetUpdateData getGetUpdateDataPort() {
        return super.getPort(GetUpdateDataPort, GetUpdateData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetUpdateData
     */
    @WebEndpoint(name = "GetUpdateDataPort")
    public GetUpdateData getGetUpdateDataPort(WebServiceFeature... features) {
        return super.getPort(GetUpdateDataPort, GetUpdateData.class, features);
    }

}
