package com.yodobashi.esa.cms.getupdatedata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-16T15:04:37.748+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/CMS/GetUpdateData", name = "GetUpdateData")
@XmlSeeAlso({ObjectFactory.class, com.yodobashi.esa.community.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetUpdateData {

    @WebResult(name = "GetUpdateData_Response", targetNamespace = "http://esa.yodobashi.com/CMS/GetUpdateData", partName = "GetUpdateData_Response")
    @WebMethod(operationName = "GetUpdateData", action = "http://sap.com/xi/WebService/soap1.1")
    public GetUpdateDataResponse getUpdateData(
        @WebParam(partName = "GetUpdateData_Req", name = "GetUpdateData_Req", targetNamespace = "http://esa.yodobashi.com/CMS/GetUpdateData")
        GetUpdateDataReq getUpdateDataReq
    );
}
