package com.yodobashi.esa.usm.deleteuniversalsession;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-11-16T18:55:56.226+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "DeleteUniversalSessionService", 
                  wsdlLocation = "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FUSM%2FDeleteUniversalSession%5EDeleteUniversalSession",
                  targetNamespace = "http://esa.yodobashi.com/USM/DeleteUniversalSession") 
public class DeleteUniversalSessionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/USM/DeleteUniversalSession", "DeleteUniversalSessionService");
    public final static QName DeleteUniversalSessionPort = new QName("http://esa.yodobashi.com/USM/DeleteUniversalSession", "DeleteUniversalSessionPort");
    static {
        URL url = null;
        try {
            url = new URL("http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FUSM%2FDeleteUniversalSession%5EDeleteUniversalSession");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeleteUniversalSessionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FUSM%2FDeleteUniversalSession%5EDeleteUniversalSession");
        }
        WSDL_LOCATION = url;
    }

    public DeleteUniversalSessionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeleteUniversalSessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeleteUniversalSessionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DeleteUniversalSession
     */
    @WebEndpoint(name = "DeleteUniversalSessionPort")
    public DeleteUniversalSession getDeleteUniversalSessionPort() {
        return super.getPort(DeleteUniversalSessionPort, DeleteUniversalSession.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteUniversalSession
     */
    @WebEndpoint(name = "DeleteUniversalSessionPort")
    public DeleteUniversalSession getDeleteUniversalSessionPort(WebServiceFeature... features) {
        return super.getPort(DeleteUniversalSessionPort, DeleteUniversalSession.class, features);
    }

}
