package com.yodobashi.esa.customer.getoutcustomerid;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-05T10:46:31.640+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/Customer/GetOutCustomerID", name = "GetOutCustomerID")
@XmlSeeAlso({ObjectFactory.class, com.yodobashi.esa.customer.structure.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetOutCustomerID {

    @WebResult(name = "GetOutCustomerID_Response", targetNamespace = "http://esa.yodobashi.com/Customer/GetOutCustomerID", partName = "GetOutCustomerID_Response")
    @WebMethod(operationName = "GetOutCustomerID", action = "http://sap.com/xi/WebService/soap1.1")
    public GetOutCustomerIDResponse getOutCustomerID(
        @WebParam(partName = "GetOutCustomerID_Req", name = "GetOutCustomerID_Req", targetNamespace = "http://esa.yodobashi.com/Customer/GetOutCustomerID")
        GetOutCustomerIDReq getOutCustomerIDReq
    );
}
