package com.yodobashi.esa.customer.getoutcustomerid;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-05T10:46:31.656+09:00
 * Generated source version: 2.4.2
 *
 */
@WebServiceClient(name = "GetOutCustomerIDService",
                  wsdlLocation = "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FGetOutCustomerID%5EGetOutCustomerID",
                  targetNamespace = "http://esa.yodobashi.com/Customer/GetOutCustomerID")
public class GetOutCustomerIDService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/Customer/GetOutCustomerID", "GetOutCustomerIDService");
    public final static QName GetOutCustomerIDPort = new QName("http://esa.yodobashi.com/Customer/GetOutCustomerID", "GetOutCustomerIDPort");
    static {
        URL url = null;
        try {
            url = new URL("http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FGetOutCustomerID%5EGetOutCustomerID");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetOutCustomerIDService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/catalog_ws/YC_COMMUNITY_BACKEND_STUB/wsdl/GetOutCustomerID20111003.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetOutCustomerIDService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetOutCustomerIDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetOutCustomerIDService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns GetOutCustomerID
     */
    @WebEndpoint(name = "GetOutCustomerIDPort")
    public GetOutCustomerID getGetOutCustomerIDPort() {
        return super.getPort(GetOutCustomerIDPort, GetOutCustomerID.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetOutCustomerID
     */
    @WebEndpoint(name = "GetOutCustomerIDPort")
    public GetOutCustomerID getGetOutCustomerIDPort(WebServiceFeature... features) {
        return super.getPort(GetOutCustomerIDPort, GetOutCustomerID.class, features);
    }

}
