package com.yodobashi.esa.auth.validateauthsession;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-08-15T18:20:19.265+09:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/AUTH/ValidateAuthSession", name = "ValidateAuthSessionV2")
@XmlSeeAlso({com.yodobashi.esa.common.ObjectFactory.class, com.yodobashi.esa.auth.type.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ValidateAuthSessionV2 {

    @WebResult(name = "ValidateAuthSessionV2_Response", targetNamespace = "http://esa.yodobashi.com/AUTH/ValidateAuthSession", partName = "ValidateAuthSessionV2_Response")
    @WebMethod(operationName = "ValidateAuthSessionV2", action = "http://sap.com/xi/WebService/soap1.1")
    public ValidateAuthSessionV2Response validateAuthSessionV2(
        @WebParam(partName = "ValidateAuthSessionV2_Req", name = "ValidateAuthSessionV2_Req", targetNamespace = "http://esa.yodobashi.com/AUTH/ValidateAuthSession")
        ValidateAuthSessionV2Req validateAuthSessionV2Req
    );
}
