package com.yodobashi.esa.customer.refoutcustomeridstatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-05T10:46:31.796+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/Customer/RefOutCustomerIDStatus", name = "RefOutCustomerIDStatus")
@XmlSeeAlso({ObjectFactory.class, com.yodobashi.esa.customer.structure.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RefOutCustomerIDStatus {

    @WebResult(name = "RefOutCustomerIDStatus_Response", targetNamespace = "http://esa.yodobashi.com/Customer/RefOutCustomerIDStatus", partName = "RefOutCustomerIDStatus_Response")
    @WebMethod(operationName = "RefOutCustomerIDStatus", action = "http://sap.com/xi/WebService/soap1.1")
    public RefOutCustomerIDStatusResponse refOutCustomerIDStatus(
        @WebParam(partName = "RefOutCustomerIDStatus_Req", name = "RefOutCustomerIDStatus_Req", targetNamespace = "http://esa.yodobashi.com/Customer/RefOutCustomerIDStatus")
        RefOutCustomerIDStatusReq refOutCustomerIDStatusReq
    );
}
