package com.yodobashi.esa.customer.getcustomerid;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-03-14T18:30:59.847+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "GetCustomerIDService", 
                  wsdlLocation = "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FGetCustomerID%5EGetCustomerID",
                  targetNamespace = "http://esa.yodobashi.com/Customer/GetCustomerID") 
public class GetCustomerIDService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/Customer/GetCustomerID", "GetCustomerIDService");
    public final static QName GetCustomerIDPort = new QName("http://esa.yodobashi.com/Customer/GetCustomerID", "GetCustomerIDPort");
    static {
        URL url = null;
        try {
            url = new URL("http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FGetCustomerID%5EGetCustomerID");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetCustomerIDService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FGetCustomerID%5EGetCustomerID");
        }
        WSDL_LOCATION = url;
    }

    public GetCustomerIDService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetCustomerIDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCustomerIDService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetCustomerID
     */
    @WebEndpoint(name = "GetCustomerIDPort")
    public GetCustomerID getGetCustomerIDPort() {
        return super.getPort(GetCustomerIDPort, GetCustomerID.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerID
     */
    @WebEndpoint(name = "GetCustomerIDPort")
    public GetCustomerID getGetCustomerIDPort(WebServiceFeature... features) {
        return super.getPort(GetCustomerIDPort, GetCustomerID.class, features);
    }

}
