package com.yodobashi.esa.cms.getupdatedatalist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-16T15:04:38.123+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/CMS/GetUpdateDataList", name = "GetUpdateDataList")
@XmlSeeAlso({com.yodobashi.esa.community.common.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetUpdateDataList {

    @WebResult(name = "GetUpdateDataList_Response", targetNamespace = "http://esa.yodobashi.com/CMS/GetUpdateDataList", partName = "GetUpdateDataList_Response")
    @WebMethod(operationName = "GetUpdateDataList", action = "http://sap.com/xi/WebService/soap1.1")
    public GetUpdateDataListResponse getUpdateDataList(
        @WebParam(partName = "GetUpdateDataList_Req", name = "GetUpdateDataList_Req", targetNamespace = "http://esa.yodobashi.com/CMS/GetUpdateDataList")
        GetUpdateDataListReq getUpdateDataListReq
    );
}
