package com.yodobashi.esa.cms.getupdatedatalist;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-16T15:04:38.123+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "GetUpdateDataListService", 
                  wsdlLocation = "file:/C:/workspace/catalog_ws/YC_COMMUNITY_DATASYNC/src/main/resources/wsdl/GetUpdateDataList20070926.wsdl",
                  targetNamespace = "http://esa.yodobashi.com/CMS/GetUpdateDataList") 
public class GetUpdateDataListService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/CMS/GetUpdateDataList", "GetUpdateDataListService");
    public final static QName GetUpdateDataListPort = new QName("http://esa.yodobashi.com/CMS/GetUpdateDataList", "GetUpdateDataListPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/catalog_ws/YC_COMMUNITY_DATASYNC/src/main/resources/wsdl/GetUpdateDataList20070926.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetUpdateDataListService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/catalog_ws/YC_COMMUNITY_DATASYNC/src/main/resources/wsdl/GetUpdateDataList20070926.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetUpdateDataListService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetUpdateDataListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetUpdateDataListService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetUpdateDataList
     */
    @WebEndpoint(name = "GetUpdateDataListPort")
    public GetUpdateDataList getGetUpdateDataListPort() {
        return super.getPort(GetUpdateDataListPort, GetUpdateDataList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetUpdateDataList
     */
    @WebEndpoint(name = "GetUpdateDataListPort")
    public GetUpdateDataList getGetUpdateDataListPort(WebServiceFeature... features) {
        return super.getPort(GetUpdateDataListPort, GetUpdateDataList.class, features);
    }

}
