package com.yodobashi.esa.customer.createoutcustomerid;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-05T10:46:31.484+09:00
 * Generated source version: 2.4.2
 *
 */
@WebServiceClient(name = "CreateOutCustomerIDService",
                  wsdlLocation = "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FCreateOutCustomerID%5ECreateOutCustomerID",
                  targetNamespace = "http://esa.yodobashi.com/Customer/CreateOutCustomerID")
public class CreateOutCustomerIDService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/Customer/CreateOutCustomerID", "CreateOutCustomerIDService");
    public final static QName CreateOutCustomerIDPort = new QName("http://esa.yodobashi.com/Customer/CreateOutCustomerID", "CreateOutCustomerIDPort");
    static {
        URL url = null;
        try {
            url = new URL("http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FCreateOutCustomerID%5ECreateOutCustomerID");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreateOutCustomerIDService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/catalog_ws/YC_COMMUNITY_BACKEND_STUB/wsdl/CreateOutCustomerID20111003.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateOutCustomerIDService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateOutCustomerIDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateOutCustomerIDService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns CreateOutCustomerID
     */
    @WebEndpoint(name = "CreateOutCustomerIDPort")
    public CreateOutCustomerID getCreateOutCustomerIDPort() {
        return super.getPort(CreateOutCustomerIDPort, CreateOutCustomerID.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateOutCustomerID
     */
    @WebEndpoint(name = "CreateOutCustomerIDPort")
    public CreateOutCustomerID getCreateOutCustomerIDPort(WebServiceFeature... features) {
        return super.getPort(CreateOutCustomerIDPort, CreateOutCustomerID.class, features);
    }

}
