package com.yodobashi.esa.customer.createoutcustomerid;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-05T10:46:31.437+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/Customer/CreateOutCustomerID", name = "CreateOutCustomerID")
@XmlSeeAlso({com.yodobashi.esa.customer.structure.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateOutCustomerID {

    @WebResult(name = "CreateOutCustomerID_Response", targetNamespace = "http://esa.yodobashi.com/Customer/CreateOutCustomerID", partName = "CreateOutCustomerID_Response")
    @WebMethod(operationName = "CreateOutCustomerID", action = "http://sap.com/xi/WebService/soap1.1")
    public CreateOutCustomerIDResponse createOutCustomerID(
        @WebParam(partName = "CreateOutCustomerID_Req", name = "CreateOutCustomerID_Req", targetNamespace = "http://esa.yodobashi.com/Customer/CreateOutCustomerID")
        CreateOutCustomerIDReq createOutCustomerIDReq
    );
}
