package com.yodobashi.esa.community.getcommunityupdatedata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-22T13:47:53.859+09:00
 * Generated source version: 2.4.2
 *
 */
@WebServiceClient(name = "GetCommunityUpdateDataService",
                  wsdlLocation = "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCOMMUNITY%2FGetCommunityUpdateData%5EGetCommunityUpdateData",
                  targetNamespace = "http://esa.yodobashi.com/COMMUNITY/GetCommunityUpdateData")
public class GetCommunityUpdateDataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/COMMUNITY/GetCommunityUpdateData", "GetCommunityUpdateDataService");
    public final static QName GetCommunityUpdateDataPort = new QName("http://esa.yodobashi.com/COMMUNITY/GetCommunityUpdateData", "GetCommunityUpdateDataPort");
    static {
        URL url = null;
        try {
            url = new URL("http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCOMMUNITY%2FGetCommunityUpdateData%5EGetCommunityUpdateData");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetCommunityUpdateDataService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/catalog_ws/YC_COMMUNITY_BACKEND_STUB/wsdl/GetCommunityUpdateData20111013.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetCommunityUpdateDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetCommunityUpdateDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCommunityUpdateDataService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns GetCommunityUpdateData
     */
    @WebEndpoint(name = "GetCommunityUpdateDataPort")
    public GetCommunityUpdateData getGetCommunityUpdateDataPort() {
        return super.getPort(GetCommunityUpdateDataPort, GetCommunityUpdateData.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCommunityUpdateData
     */
    @WebEndpoint(name = "GetCommunityUpdateDataPort")
    public GetCommunityUpdateData getGetCommunityUpdateDataPort(WebServiceFeature... features) {
        return super.getPort(GetCommunityUpdateDataPort, GetCommunityUpdateData.class, features);
    }

}
