package com.yodobashi.esa.community.getcommunityupdatedata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-22T13:47:53.796+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/COMMUNITY/GetCommunityUpdateData", name = "GetCommunityUpdateData")
@XmlSeeAlso({ObjectFactory.class, com.yodobashi.esa.community.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetCommunityUpdateData {

    @WebResult(name = "GetCommunityUpdateData_Response", targetNamespace = "http://esa.yodobashi.com/COMMUNITY/GetCommunityUpdateData", partName = "GetCommunityUpdateData_Response")
    @WebMethod(operationName = "GetCommunityUpdateData", action = "http://sap.com/xi/WebService/soap1.1")
    public GetCommunityUpdateDataResponse getCommunityUpdateData(
        @WebParam(partName = "GetCommunityUpdateData_Req", name = "GetCommunityUpdateData_Req", targetNamespace = "http://esa.yodobashi.com/COMMUNITY/GetCommunityUpdateData")
        GetCommunityUpdateDataReq getCommunityUpdateDataReq
    );
}
