package com.yodobashi.esa.customer.getoutcustomeridshareinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-11-14T11:38:09.641+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/Customer/GetOutCustomerIDShareInfo", name = "GetOutCustomerIDShareInfo")
@XmlSeeAlso({ObjectFactory.class, com.yodobashi.esa.customer.structure.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetOutCustomerIDShareInfo {

    @WebResult(name = "GetOutCustomerIDShareInfo_Response", targetNamespace = "http://esa.yodobashi.com/Customer/GetOutCustomerIDShareInfo", partName = "GetOutCustomerIDShareInfo_Response")
    @WebMethod(operationName = "GetOutCustomerIDShareInfo", action = "http://sap.com/xi/WebService/soap1.1")
    public GetOutCustomerIDShareInfoResponse getOutCustomerIDShareInfo(
        @WebParam(partName = "GetOutCustomerIDShareInfo_Req", name = "GetOutCustomerIDShareInfo_Req", targetNamespace = "http://esa.yodobashi.com/Customer/GetOutCustomerIDShareInfo")
        GetOutCustomerIDShareInfoReq getOutCustomerIDShareInfoReq
    );
}
