package com.yodobashi.esa.customer.getoutcustomeridshareinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-11-14T11:38:09.650+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "GetOutCustomerIDShareInfoService", 
                  wsdlLocation = "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FGetOutCustomerIDShareInfo%5EGetOutCustomerIDShareInfo",
                  targetNamespace = "http://esa.yodobashi.com/Customer/GetOutCustomerIDShareInfo") 
public class GetOutCustomerIDShareInfoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/Customer/GetOutCustomerIDShareInfo", "GetOutCustomerIDShareInfoService");
    public final static QName GetOutCustomerIDShareInfoPort = new QName("http://esa.yodobashi.com/Customer/GetOutCustomerIDShareInfo", "GetOutCustomerIDShareInfoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FGetOutCustomerIDShareInfo%5EGetOutCustomerIDShareInfo");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetOutCustomerIDShareInfoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FGetOutCustomerIDShareInfo%5EGetOutCustomerIDShareInfo");
        }
        WSDL_LOCATION = url;
    }

    public GetOutCustomerIDShareInfoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetOutCustomerIDShareInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetOutCustomerIDShareInfoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetOutCustomerIDShareInfo
     */
    @WebEndpoint(name = "GetOutCustomerIDShareInfoPort")
    public GetOutCustomerIDShareInfo getGetOutCustomerIDShareInfoPort() {
        return super.getPort(GetOutCustomerIDShareInfoPort, GetOutCustomerIDShareInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetOutCustomerIDShareInfo
     */
    @WebEndpoint(name = "GetOutCustomerIDShareInfoPort")
    public GetOutCustomerIDShareInfo getGetOutCustomerIDShareInfoPort(WebServiceFeature... features) {
        return super.getPort(GetOutCustomerIDShareInfoPort, GetOutCustomerIDShareInfo.class, features);
    }

}
