package com.yodobashi.esa.usm.searchuniversalsession;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-03-22T18:36:21.028+09:00
 * Generated source version: 2.4.2
 *
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/USM/SearchUniversalSession", name = "SearchUniversalSession")
@XmlSeeAlso({com.yodobashi.esa.common.ObjectFactory.class, com.yodobashi.esa.usm.type.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SearchUniversalSession {

    @WebResult(name = "SearchUniversalSession_Response", targetNamespace = "http://esa.yodobashi.com/USM/SearchUniversalSession", partName = "SearchUniversalSession_Response")
    @WebMethod(operationName = "SearchUniversalSession", action = "http://sap.com/xi/WebService/soap1.1")
    public SearchUniversalSessionResponse searchUniversalSession(
        @WebParam(partName = "SearchUniversalSession_Req", name = "SearchUniversalSession_Req", targetNamespace = "http://esa.yodobashi.com/USM/SearchUniversalSession")
        SearchUniversalSessionReq searchUniversalSessionReq
    );
}
