package com.yodobashi.esa.usm.searchuniversalsession;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-03-22T18:36:21.044+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "SearchUniversalSessionService", 
                  wsdlLocation = "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FUSM%2FSearchUniversalSession%5ESearchUniversalSession",
                  targetNamespace = "http://esa.yodobashi.com/USM/SearchUniversalSession") 
public class SearchUniversalSessionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/USM/SearchUniversalSession", "SearchUniversalSessionService");
    public final static QName SearchUniversalSessionPort = new QName("http://esa.yodobashi.com/USM/SearchUniversalSession", "SearchUniversalSessionPort");
    static {
        URL url = null;
        try {
            url = new URL("http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FUSM%2FSearchUniversalSession%5ESearchUniversalSession");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SearchUniversalSessionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FUSM%2FSearchUniversalSession%5ESearchUniversalSession");
        }
        WSDL_LOCATION = url;
    }

    public SearchUniversalSessionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SearchUniversalSessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchUniversalSessionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SearchUniversalSession
     */
    @WebEndpoint(name = "SearchUniversalSessionPort")
    public SearchUniversalSession getSearchUniversalSessionPort() {
        return super.getPort(SearchUniversalSessionPort, SearchUniversalSession.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchUniversalSession
     */
    @WebEndpoint(name = "SearchUniversalSessionPort")
    public SearchUniversalSession getSearchUniversalSessionPort(WebServiceFeature... features) {
        return super.getPort(SearchUniversalSessionPort, SearchUniversalSession.class, features);
    }

}
