package com.yodobashi.esa.customer.updateoutcustomeridstatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-05T10:46:31.937+09:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://esa.yodobashi.com/Customer/UpdateOutCustomerIDStatus", name = "UpdateOutCustomerIDStatus")
@XmlSeeAlso({ObjectFactory.class, com.yodobashi.esa.customer.structure.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateOutCustomerIDStatus {

    @WebResult(name = "UpdateOutCustomerIDStatus_Response", targetNamespace = "http://esa.yodobashi.com/Customer/UpdateOutCustomerIDStatus", partName = "UpdateOutCustomerIDStatus_Response")
    @WebMethod(operationName = "UpdateOutCustomerIDStatus", action = "http://sap.com/xi/WebService/soap1.1")
    public UpdateOutCustomerIDStatusResponse updateOutCustomerIDStatus(
        @WebParam(partName = "UpdateOutCustomerIDStatus_Req", name = "UpdateOutCustomerIDStatus_Req", targetNamespace = "http://esa.yodobashi.com/Customer/UpdateOutCustomerIDStatus")
        UpdateOutCustomerIDStatusReq updateOutCustomerIDStatusReq
    );
}
