package com.yodobashi.esa.customer.updateoutcustomeridstatus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-05T10:46:31.937+09:00
 * Generated source version: 2.4.2
 *
 */
@WebServiceClient(name = "UpdateOutCustomerIDStatusService",
                  wsdlLocation = "http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FUpdateOutCustomerIDStatus%5EUpdateOutCustomerIDStatus",
                  targetNamespace = "http://esa.yodobashi.com/Customer/UpdateOutCustomerIDStatus")
public class UpdateOutCustomerIDStatusService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esa.yodobashi.com/Customer/UpdateOutCustomerIDStatus", "UpdateOutCustomerIDStatusService");
    public final static QName UpdateOutCustomerIDStatusPort = new QName("http://esa.yodobashi.com/Customer/UpdateOutCustomerIDStatus", "UpdateOutCustomerIDStatusPort");
    static {
        URL url = null;
        try {
            url = new URL("http://euc3sx1:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=Community1&Interface=http%3A%2F%2Fesa.yodobashi.com%2FCustomer%2FUpdateOutCustomerIDStatus%5EUpdateOutCustomerIDStatus");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UpdateOutCustomerIDStatusService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/catalog_ws/YC_COMMUNITY_BACKEND_STUB/wsdl/UpdateOutCustomerIDStatus20111003.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UpdateOutCustomerIDStatusService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UpdateOutCustomerIDStatusService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateOutCustomerIDStatusService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns UpdateOutCustomerIDStatus
     */
    @WebEndpoint(name = "UpdateOutCustomerIDStatusPort")
    public UpdateOutCustomerIDStatus getUpdateOutCustomerIDStatusPort() {
        return super.getPort(UpdateOutCustomerIDStatusPort, UpdateOutCustomerIDStatus.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateOutCustomerIDStatus
     */
    @WebEndpoint(name = "UpdateOutCustomerIDStatusPort")
    public UpdateOutCustomerIDStatus getUpdateOutCustomerIDStatusPort(WebServiceFeature... features) {
        return super.getPort(UpdateOutCustomerIDStatusPort, UpdateOutCustomerIDStatus.class, features);
    }

}
